### ISSUE TITLE
Different visibility for different users

### ISSUE THREAD

**Issue by QuangTran304** [SamanthaGuillemette/SOEN390#14]
**Description**: 
As a user, I want to see only the information that are relevant to me so that I am not overwhelmed by the unnecessary information OR having accessed on sensitive information about other users.

**Example**:
For example, while a doctor may see everything, an immigration officer should probably see only identifying information and COVID-19 status, and nothing else.

**Additional Details**:
- [x] An admin user may have a powerful dashboard with all the controls.
- [x] A patient-user may have a simplified web page to view his/her Covid-19 statistics and to modify basic information.

**Acceptance criteria**:
Given: The user is logged in. 
When: The user is on the main page.
Then: The web app only displays information that is relevant to the user that is logged in.

**Sub-task**:

- [x] #256
- [x] Front-end display
- [x] Back-end connection

**Comment by QuangTran304** [comment]
completed visibility for Doctors

**Comment by QuangTran304** [comment]
DONE visibilities for ALL users
