### ISSUE TITLE
Tasks Left for App

### ISSUE THREAD

**Issue by MarwaKhalid** [SamanthaGuillemette/SOEN390#306]
Client App:
- [x] Diary (Sam)
- [x] NOTE: PUSHED TO SPRINT 5, Doctor Info, some info arent in the database & Diary in backend (#233 )
- [x] NOTE: PUSHED TO SPRINT 5, Notify if 2 or more people are in same postal stated in their diary
- [x] Notify to update status everyday (Laila)
- [x]  #335
- [x] #333 
- [x] #327 
- [x] #4 

Admin App:
- [x] Finish Notifications (Saleha & Ali)
- [x] Dashboard line chart (Quang)
- [x] Appointments (Quang)
- [x] Visibility based on logged in user (Laila & Quang)
- [x] CSS for News & Events Page (Hoda) #329 
- [x] #295 
- [x] NOTE: PUSHED TO SPRINT 5, #339

Both Apps:
- [ ] Fix tests (Ali)

**Comment by QuangTran304** [comment]
I was planning to add the 2 datasets on the line chart (New cases & Active cases) but since this chart needs daily active data and a huge amount of newly reported patients, I'll drop it. Our system is not sophisticated enough.

**Comment by SamanthaGuillemette** [comment]
all done or pushed to sprint 5!
