### ISSUE TITLE
LogIn /  SignUp function

### ISSUE THREAD

**Issue by QuangTran304** [SamanthaGuillemette/SOEN390#7]
**Description**: 
As a user, I want to have a login / signup system so that users with different roles can log into their dashboard to view the appropriate contents.

**Additional details**:
- [x] Login / SignUp page for admin users (health officials, doctors, etc...)
- [x] Login / SignUp page for clients (patients, guests)

**Acceptance criteria**:
Given: User is on the login page and inputs their password and email correctly
When: User clicks on the 'login' button
Then: User will be redirected to the dashboard

**Sub-task**:

- [x] Front-end display
- [x] Back-end connection
